default: &default
  adapter: postgresql
  encoding: unicode
  username: andrelinoge
  password: qwe123
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: setool_development


staging:
  <<: *default
  database: setool_staging

test:
  <<: *default
  database: setool_test

production:
  <<: *default
  database: setool_production
  username: andrelinoge
  password: qwe123
